### ISSUE TITLE
Test failures on OSX with Python 2

### ISSUE THREAD

**Issue by jakevdp** [pyamg/pyamg#165]
I'm on OSX 10.8, and the pyamg test suite shows failures under Python 2.6 and 2.7. The failures do not appear in Python 3.x

Here's the environment I'm using for testing:

```
$ conda update conda
$ conda create -n test-pyamg python=2.7 numpy scipy gcc nose
$ source activate test-pyamg
$ python setup.py install
$ cd /tmp
$ nosetests pyamg
...............F....................F..............................................FF..........................................................................................................
======================================================================
FAIL: test_nonhermitian (test_aggregation.TestComplexSolverPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/pyamg/aggregation/tests/test_aggregation.py", line 539, in test_nonhermitian
    assert(avg_convergence_ratio < 0.7)
AssertionError

======================================================================
FAIL: test_nonhermitian (test_rootnode.TestComplexSolverPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/pyamg/aggregation/tests/test_rootnode.py", line 514, in test_nonhermitian
    assert(avg_convergence_ratio < 0.8)
AssertionError

======================================================================
FAIL: test_gmres (test_krylov.TestKrylov)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/pyamg/krylov/tests/test_krylov.py", line 117, in test_gmres
    err_msg=err_msg)
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/numpy/testing/utils.py", line 892, in assert_array_almost_equal
    precision=decimal)
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/numpy/testing/utils.py", line 713, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not almost equal to 6 decimals
Householder GMRES and MGS GMRES gave different results for small matrix
(mismatch 100.0%)
 x: array([ 0.290968+0.153989j,  0.586837+0.333348j,  0.463363-0.153248j,
       -0.367928+0.250131j])
 y: array([ 0.475121+0.081836j,  0.596034+0.195189j,  0.586335-0.045095j,
        0.156787+0.061668j])

======================================================================
FAIL: test_krylov (test_krylov.TestKrylov)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/pyamg/krylov/tests/test_krylov.py", line 157, in test_krylov
    err_msg='Oblique Krylov Method Failed Test')
  File "/Users/jakevdp/anaconda/envs/test-pyamg/lib/python2.7/site-packages/numpy/testing/utils.py", line 355, in assert_equal
    raise AssertionError(msg)
AssertionError: 
Items are not equal: Oblique Krylov Method Failed Test
 ACTUAL: False
 DESIRED: True

----------------------------------------------------------------------
Ran 191 tests in 32.498s

FAILED (failures=4)
```

**Comment by lukeolson** [comment]
Our conda tester looks like it's passing.  Which pyamg version are you using?  (these were known fails before, so I'm wondering why they're showing up again)

**Comment by jakevdp** [comment]
This is on the current github master:
```
$ git log --pretty=oneline | head -5
621d63411895898660e5ea078840118905bec061 fix coefficients spelling
6db634695feb1b040bc741c6c62cc4118ca84371 update todo
3ddbe063a7dd7789d0da6cd3c945b9527db3c1c9 change ignore; update version
fd7463df13553d0aa282741eb756efba76d6d1b5 add NPY_ARRAY_F_CONTIGUOUS define for numpy 1.6 support
40ff7bc6afe54840c233324cfac070e1952cb636 fix empty import issue

```

**Comment by jakevdp** [comment]
I just tried this on a linux box, and the errors don't happen. Seems to be OSX only, which is why travis is not catching them.

**Comment by lukeolson** [comment]
closing ... nothing to fix(?)
