### ISSUE TITLE
Test failures on Windows

### ISSUE THREAD

**Issue by jakevdp** [pyamg/pyamg#168]
I'm trying to [build a conda package](https://github.com/conda-forge/staged-recipes/pull/273) for pyamg using the 3.0.2 release from pypi, and I'm finding lots of test failures on Windows. You can see the tracebacks here: https://ci.appveyor.com/project/conda-forge/staged-recipes/build/1.0.728

For example:

```
======================================================================
ERROR: test_nonhermitian (test_aggregation.TestComplexSolverPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\multilevel.py", line 408, in solve
    callback=callback, residuals=residuals)[0]
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres.py", line 107, in gmres
    **kwargs)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres_householder.py", line 332, in gmres_householder
    y = sp.linalg.solve(H[0:(inner+1), 0:(inner+1)], g[0:(inner+1)])
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 79, in solve
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\_lib\_util.py", line 187, in _asarray_validated
    a = toarray(a)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 668, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\aggregation\tests\test_aggregation.py", line 534, in test_nonhermitian
    **SA_solve_args)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\multilevel.py", line 427, in solve
    callback=callback)[0]
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres.py", line 107, in gmres
    **kwargs)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres_householder.py", line 332, in gmres_householder
    y = sp.linalg.solve(H[0:(inner+1), 0:(inner+1)], g[0:(inner+1)])
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 79, in solve
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\_lib\_util.py", line 187, in _asarray_validated
    a = toarray(a)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 668, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

======================================================================
ERROR: test_nonhermitian (test_rootnode.TestComplexSolverPerformance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\multilevel.py", line 408, in solve
    callback=callback, residuals=residuals)[0]
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres.py", line 107, in gmres
    **kwargs)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres_householder.py", line 332, in gmres_householder
    y = sp.linalg.solve(H[0:(inner+1), 0:(inner+1)], g[0:(inner+1)])
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 79, in solve
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\_lib\_util.py", line 187, in _asarray_validated
    a = toarray(a)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 668, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\aggregation\tests\test_rootnode.py", line 508, in test_nonhermitian
    **SA_solve_args)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\multilevel.py", line 427, in solve
    callback=callback)[0]
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres.py", line 107, in gmres
    **kwargs)
  File "C:\Miniconda\envs\_test\lib\site-packages\pyamg\krylov\_gmres_householder.py", line 332, in gmres_householder
    y = sp.linalg.solve(H[0:(inner+1), 0:(inner+1)], g[0:(inner+1)])
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\linalg\basic.py", line 79, in solve
    a1 = _asarray_validated(a, check_finite=check_finite)
  File "C:\Miniconda\envs\_test\lib\site-packages\scipy\_lib\_util.py", line 187, in _asarray_validated
    a = toarray(a)
  File "C:\Miniconda\envs\_test\lib\site-packages\numpy\lib\function_base.py", line 668, in asarray_chkfinite
    "array must not contain infs or NaNs")
ValueError: array must not contain infs or NaNs

----------------------------------------------------------------------
Ran 191 tests in 25.731s

FAILED (errors=2)
TESTS FAILED: pyamg-3.0.2-np110py35_0
```

**Comment by lukeolson** [comment]
Ok, I'm working on a Conda test for travis -- I'm not sure why you're getting these errors
