### ISSUE TITLE
Blackbox solver raises exception

### ISSUE THREAD

**Issue by lahwaacz** [pyamg/pyamg#202]
When I try to run the [blackbox solver](https://github.com/pyamg/pyamg/wiki/Examples#Blackbox%20Solver) example, I get the following error:

```
  Detected a Hermitian matrix
Traceback (most recent call last):
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/blackbox.py", line 213, in solver
    keep=config['keep'])
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/aggregation/aggregation.py", line 283, in smoothed_aggregation_solver
    improve_candidates, diagonal_dominance, keep)
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/aggregation/aggregation.py", line 322, in extend_hierarchy
    C = evolution_strength_of_connection(A, B, **kwargs)
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/strength.py", line 716, in evolution_strength_of_connection
    np.imag(Atilde.data) * np.imag(data)
ValueError: output array is read-only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pyamg_example.py", line 7, in <module>
    x = solve(A,b,verb=True,tol=1e-8)
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/blackbox.py", line 288, in solve
    existing_solver = solver(A, config)
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/blackbox.py", line 215, in solver
    raise TypeError('Failed generating smoothed_aggregation_solver')
TypeError: Failed generating smoothed_aggregation_solver
```

I have Python 3.6.1, NumPy 1.13.0 and SciPy 0.19.0.

**Comment by lukeolson** [comment]
Does this example work?

```
import pyamg
import numpy as np

A = pyamg.gallery.poisson((50,50), format='csr')
b = np.random.rand(A.shape[0])

x = pyamg.blackbox.solve(A, b)
```

**Comment by lahwaacz** [comment]
Yes, it does. But if I change the problem size to 100x100 as in the tutorial, I get the same error.

**Comment by lukeolson** [comment]
I'm unable to reproduce with (100, 100) (and with the exact example from the wiki).  Does it fail if you simply call `pyamg.smoothed_aggregation_solver`?

```
ml = pyamg.smoothed_aggregation_solver(A)
res = []
x = ml.solve(b, residuals=res)
print(res)
```

**Comment by lahwaacz** [comment]
That works because it apparently avoids the problematic code path. Upon further investigation, both `np.imag(Atilde.data)` and `np.imag(data)` return non-writeable arrays, even for 50x50. So apparently for 100x100, the `*` operator tries to do the operation in place. If I substitute `np.imag(Atilde.data) * np.imag(data)` with `np.multiply( np.imag(Atilde.data), np.imag(data) )`, it seems to always do a copy for the result.

**Comment by lukeolson** [comment]
https://github.com/numpy/numpy/issues/9679

**Comment by lukeolson** [comment]
this has been backported to the numpy version in question

https://github.com/numpy/numpy/pull/9732
