### ISSUE TITLE
Non-symmetric adaptive_sa_solver does not work

### ISSUE THREAD

**Issue by lahwaacz** [pyamg/pyamg#205]
This code
```python
import pyamg
A = pyamg.gallery.poisson((50,50), format='csr')
ml, work = pyamg.aggregation.adaptive_sa_solver(A, symmetry="nonsymmetric")
```
throws this error:
```
Traceback (most recent call last):
  File "pyamg_example.py", line 3, in <module>
    ml, work = pyamg.aggregation.adaptive_sa_solver(A, symmetry="nonsymmetric")
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/aggregation/adaptive.py", line 252, in adaptive_sa_solver
    prepostsmoother, smooth, strength, work)
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/aggregation/adaptive.py", line 546, in initial_setup_stage
    relax(A_l, x)  # step 4h
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/aggregation/adaptive.py", line 389, in relax
    iterations=candidate_iters, sweep='symmetric')
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/relaxation/relaxation.py", line 325, in gauss_seidel
    A, x, b = make_system(A, x, b, formats=['csr', 'bsr'])
  File "/home/klinkovsky/.local/lib/python3.6/site-packages/pyamg-3.2.1.dev0+191dcdf-py3.6-linux-x86_64.egg/pyamg/relaxation/relaxation.py", line 91, in make_system
    raise ValueError('x has invalid dimensions')
ValueError: x has invalid dimensions
```

**Comment by ben-s-southworth** [comment]
The adaptive SA solver is a bit finicky as a method, not just our
implementation. Reproducing results from the original paper has
been difficult. This of course is a bug that I will take a look at later
this week, but just a forewarning on aSA.
