### ISSUE TITLE
Installation/usage Error

### ISSUE THREAD

**Issue by ArashMehraban** [pyamg/pyamg#216]
Hi,

pyamg installation seemed to have done its job but when I want to use it I get an error.
I am using Ubuntu 14.04. Here is the steps I took:

1) Downloaded and Extracted: pyamg-3.3.2.tar.gz
2) In  pyamg-3.3.2 folder, I ran  
     sudo python setup.py install

Then,

>>> import pyamg

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import pyamg
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/__init__.py", line 12, in <module>
    from .classical import ruge_stuben_solver
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/classical/__init__.py", line 4, in <module>
    from .classical import *
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/classical/classical.py", line 9, in <module>
    from pyamg.relaxation.smoothing import change_smoothers
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/relaxation/smoothing.py", line 6, in <module>
    from . import relaxation
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/relaxation/relaxation.py", line 10, in <module>
    from pyamg.util.utils import type_prep, get_diagonal, get_block_diag
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/util/__init__.py", line 6, in <module>
    from .linalg import *
  File "/usr/local/lib/python2.7/dist-packages/pyamg-3.3.2-py2.7-linux-x86_64.egg/pyamg/util/linalg.py", line 9, in <module>
    from scipy.linalg.lapack import _compute_lwork
ImportError: cannot import name _compute_lwork

**Comment by lukeolson** [comment]
I'll look into it -- which versions of numpy, scipy are you using?

**Comment by lukeolson** [comment]
This is likely the source: https://github.com/pyamg/pyamg/pull/209

**Comment by ArashMehraban** [comment]
Python 2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4] on linux2
Type "copyright", "credits" or "license()" for more information.
>>> import scipy
>>> scipy.__version__
'0.13.3'
>>> import numpy
>>> numpy.__version__
'1.8.2'
>>>

**Comment by ArashMehraban** [comment]
I have fixed the issue but I just let you know what happened.
I first downloaded the source code and tried **sudo python setup.py install** command to install it and it failed. I updated the **numpy** and **scipy** but the error still remained. 

Without removing that installation, I used the **pip install --upgrade pyamg** command to reinstall the package, but the problem still persisted. So I pip uninstalled it. The interesting thing is that it gave me a message that it was removed but apparently it wasn't. The **pyamg** and **pyamg-3.3.2.egg-info** were still in the **/usr/local/lib/python2.7/dist-packages**
So I manually removed those folders and reinstalled with **pip install --upgrade pyamg** and it worked.
