### ISSUE TITLE
Missing functions for matrices with 64-bit indices

### ISSUE THREAD

**Issue by lahwaacz** [pyamg/pyamg#277]
I have a 471526400 x 471526400 matrix with 3099301688 non-zeros. Hence, 64-bit indices are needed in the CSR representation. However, some necessary functions seem to expect 32-bit indices:
```
Traceback (most recent call last):
  File "./solve_pyamg.py", line 53, in <module>
    ml = pyamg.ruge_stuben_solver(A, CF="RS")
  File "/usr/lib/python3.8/site-packages/pyamg/classical/classical.py", line 110, in ruge_stuben_solver
    extend_hierarchy(levels, strength, CF, keep)
  File "/usr/lib/python3.8/site-packages/pyamg/classical/classical.py", line 134, in extend_hierarchy
    C = classical_strength_of_connection(A, **kwargs)
  File "/usr/lib/python3.8/site-packages/pyamg/strength.py", line 197, in classical_strength_of_connection
    amg_core.classical_strength_of_connection_abs(
TypeError: classical_strength_of_connection_abs(): incompatible function arguments. The following argument types are supported:
    1. (n_row: int, theta: float, Ap: numpy.ndarray[int32], Aj: numpy.ndarray[int32], Ax: numpy.ndarray[float32], Sp: numpy.ndarray[int32], Sj: numpy.ndarray[int32], Sx: numpy.ndarray[float32]) -> None
    2. (n_row: int, theta: float, Ap: numpy.ndarray[int32], Aj: numpy.ndarray[int32], Ax: numpy.ndarray[float64], Sp: numpy.ndarray[int32], Sj: numpy.ndarray[int32], Sx: numpy.ndarray[float64]) -> None
    3. (n_row: int, theta: float, Ap: numpy.ndarray[int32], Aj: numpy.ndarray[int32], Ax: numpy.ndarray[complex64], Sp: numpy.ndarray[int32], Sj: numpy.ndarray[int32], Sx: numpy.ndarray[complex64]) -> None
    4. (n_row: int, theta: float, Ap: numpy.ndarray[int32], Aj: numpy.ndarray[int32], Ax: numpy.ndarray[complex128], Sp: numpy.ndarray[int32], Sj: numpy.ndarray[int32], Sx: numpy.ndarray[complex128]) -> None

Invoked with: 471526400, 0.25, array([         0,          1,          2, ..., 3099301686, 3099301687,
       3099301688]), array([        0,         1,         2, ..., 471526397, 471526398,
       471526399]), array([1., 1., 1., ..., 1., 1., 1.]), array([0, 0, 0, ..., 0, 0, 0]), array([0, 0, 0, ..., 0, 0, 0]), array([0., 0., 0., ..., 0., 0., 0.])
```

**Comment by lahwaacz** [comment]
Hmm. Technically, it would be fine to store column indices as 32-bit since 471526400 is in the range. But if I do
```python
# csr = my instance of scipy.sparse.csr_matrix
csr.indices = csr.indices.astype(numpy.int32)
csr.indptr = csr.indptr.astype(numpy.int32)
print(csr.nnz)
print(len(csr.indices))
```
I get -1195665608 for `csr.nnz` and 3099301688 for `len(csr.indices)`. So there seems to be also some bug/limitation in scipy...
