### ISSUE TITLE
Support for python3.13

### ISSUE THREAD

**Issue by carlosal1015** [pyamg/pyamg#294]
Hi, pyamg core team, I tried to install the latest version of your software with python3.10. I am not sure if this version will be support soon.
I am sharing this error, that [worked fine](https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=python-pyamg) with the [previous version in Arch Linux distribution](https://aur.archlinux.org/packages/python-pyamg).

```console
(1/1) Arming ConditionNeedsUpdate...
==> Retrieving sources...
  -> Downloading v4.2.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119  100   119    0     0    660      0 --:--:-- --:--:-- --:--:--   661
100 3808k    0 3808k    0     0  6420k      0 --:--:-- --:--:-- --:--:--  9.8M
==> Validating source files with sha512sums...
    v4.2.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v4.2.0.tar.gz with bsdtar
==> Starting build()...
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 33, in __getattr__
    return next(
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 387, in _parse_attr
    return getattr(StaticModule(module_name), attr_name)
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 41, in __getattr__
    raise AttributeError(
AttributeError: pyamg has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/makepkg/python-pyamg/src/pyamg-4.2.0/setup.py", line 43, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 778, in parse_config_files
    parse_configuration(self, self.command_options,
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 157, in parse_configuration
    meta.parse()
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 463, in parse
    section_parser_method(section_options)
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 436, in parse_section
    self[name] = value
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 220, in __setitem__
    value = parser(value)
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 557, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/usr/lib/python3.10/site-packages/setuptools/config.py", line 390, in _parse_attr
    module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/tmp/makepkg/python-pyamg/src/pyamg-4.2.0/pyamg/__init__.py", line 8, in <module>
    from .version import version_tuple as __version_tuple__
ModuleNotFoundError: No module named 'pyamg.version'
```

**Comment by lukeolson** [comment]
I rolled out 4.2.0 a moment ago and it looks like the `sdist` is missing something.  I'll take a look...

**Comment by carlosal1015** [comment]
Thank you.

**Comment by lukeolson** [comment]
ok, here's the issue (mainly for own notes): the github assets are not an actual dist, just a snapshot of the directory (`git-archive` I'm guessing).  However for versioning, `setuptools_scm` requires access to the git tags (`git describe --tags`) which is not available.

Options:

- dump setuptools_scm
- https://pypi.org/project/setuptools-scm-git-archive/
- `parentdir_prefix_version` in setuptools_scm
- `fallback_version` in setuptools_scm
- hack some other metadata together

The `fallback_version` option is predictable, so I went with that (for now).

0edf1d1dea0b100720af59b6357459176ded5ab1

**Comment by lukeolson** [comment]
I'll fix one other release issue and bump to 4.1.1 before closing this...

**Comment by carlosal1015** [comment]
Thank you for the efforts, I am going finish testing and verification the package from this [key]( https://github.com/lukeolson.gpg). I will upgrade the progress in minutes/hours.

**Comment by lukeolson** [comment]
@carlosal1015 -- did you encounter an issue?

**Comment by carlosal1015** [comment]
The same error appears again but with latest version
```
==> Starting build()...
* Building wheel...
/usr/lib/python3.13/site-packages/setuptools_scm/_integration/version_inference.py:51: UserWarning: version of pyamg already set
  warnings.warn(self.message)
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/setuptools/config/expand.py", line 71, in __getattr__
    return next(
        ast.literal_eval(value)
        for target, value in self._find_assignments()
        if isinstance(target, ast.Name) and target.id == attr
    )
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/setuptools/config/expand.py", line 185, in read_attr
    value = getattr(StaticModule(module_name, spec), attr_name)
  File "/usr/lib/python3.13/site-packages/setuptools/config/expand.py", line 77, in __getattr__
    raise AttributeError(f"{self.name} has no attribute {attr}") from e
AttributeError: pyamg has no attribute __version__

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
    main()
    ~~~~^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
                             ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/pyproject_hooks/_in_process/_in_process.py", line 280, in build_wheel
    return _build_backend().build_wheel(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        wheel_directory, config_settings, metadata_directory
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 432, in build_wheel
    return _build(['bdist_wheel'])
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 423, in _build
    return self._build_with_temp_dir(
           ~~~~~~~~~~~~~~~~~~~~~~~~~^
        cmd,
        ^^^^
    ...<3 lines>...
        self._arbitrary_args(config_settings),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 404, in _build_with_temp_dir
    self.run_setup()
    ~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/build_meta.py", line 317, in run_setup
    exec(code, locals())
    ~~~~^^^^^^^^^^^^^^^^
  File "<string>", line 43, in <module>
  File "/usr/lib/python3.13/site-packages/setuptools/__init__.py", line 115, in setup
    return distutils.core.setup(**attrs)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/_distutils/core.py", line 160, in setup
    dist.parse_config_files()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/dist.py", line 752, in parse_config_files
    setupcfg.parse_configuration(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self, self.command_options, ignore_option_errors=ignore_option_errors
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 188, in parse_configuration
    meta.parse()
    ~~~~~~~~~~^^
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 502, in parse
    section_parser_method(section_options)
    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 477, in parse_section
    self[name] = value
    ~~~~^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 294, in __setitem__
    parsed = self.parsers.get(option_name, lambda x: x)(value)
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 600, in _parse_version
    return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
                          ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/config/setupcfg.py", line 419, in _parse_attr
    return expand.read_attr(attr_desc, package_dir, root_dir)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/setuptools/config/expand.py", line 190, in read_attr
    module = _load_spec(spec, module_name)
  File "/usr/lib/python3.13/site-packages/setuptools/config/expand.py", line 211, in _load_spec
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1026, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/build/python-pyamg/src/pyamg/pyamg/__init__.py", line 8, in <module>
    from .version import version_tuple as __version_tuple__
ModuleNotFoundError: No module named 'pyamg.version'

ERROR Backend subprocess exited when trying to invoke build_wheel
```

Also I tried `sed -i '12 a fallback_version = "v5.3.0"' pyamg/pyproject.toml` but does not help.

**Comment by lukeolson** [comment]
> > [@carlosal1015](https://github.com/carlosal1015) -- did you encounter an issue?
> 
> Yes, almost from traceback is exactly same error, also I tried to solve the issue as before adding the field version fallback in `pyproject.toml` but does not work.

thanks for reporting this (and sorry for the breakage).  I'll dig in and loop back.

If you're in a virtual env, could you report your `pip list`?

**Comment by carlosal1015** [comment]
#453 fix the problem from side.

https://aur.archlinux.org/cgit/aur.git/commit/?h=python-pyamg&id=3efa3184eea34c5d9be9ae79dbd87304801013f7
