### ISSUE TITLE
pip import issue

### ISSUE THREAD

**Issue by bensworth** [pyamg/pyamg#302]
I tried to install PyAMG in a conda environment using pip, but cannot import:
```
>>> import pyamg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/__init__.py", line 12, in <module>
    from .classical import ruge_stuben_solver
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/classical/__init__.py", line 4, in <module>
    from .classical import *
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/classical/classical.py", line 9, in <module>
    from pyamg.relaxation.smoothing import change_smoothers
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/relaxation/smoothing.py", line 5, in <module>
    from . import relaxation
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/relaxation/relaxation.py", line 10, in <module>
    from pyamg.util.utils import type_prep, get_diagonal, get_block_diag
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/util/__init__.py", line 7, in <module>
    from .utils import *
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/util/utils.py", line 13, in <module>
    import pyamg.amg_core
  File "/opt/anaconda3/lib/python3.8/site-packages/pyamg/amg_core/__init__.py", line 5, in <module>
    from .evolution_strength import *
ImportError: dlopen(/opt/anaconda3/lib/python3.8/site-packages/pyamg/amg_core/evolution_strength.cpython-38-darwin.so, 2): Symbol not found: __ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm
  Referenced from: /opt/anaconda3/lib/python3.8/site-packages/pyamg/amg_core/evolution_strength.cpython-38-darwin.so
  Expected in: /usr/lib/libstdc++.6.dylib
 in /opt/anaconda3/lib/python3.8/site-packages/pyamg/amg_core/evolution_strength.cpython-38-darwin.so
```
Forced a reinstall/upgrade too via `pip install --upgrade --force-reinstall pyamg` but the problem persisted

**Comment by bensworth** [comment]
Oops, my force reinstall was using the wrong pip. Forcing a reinstall fixed the issue.

**Comment by lukeolson** [comment]
Sounds good -- let me know if you run into problems again.  Often `Symbol not found: __ZNKSt7_...` types of things indicates a problem with the wrong compiler or incorrect Python version.

**Comment by Sushmey** [comment]
Hi there, I was trying to set up pyamg on my local but keep running into this same error. I've tried both ways of installing, 
`pip install pyamg` and `pip install .` 

Tried uninstalling, reinstalling and force reinstalling but to no avail.

Python version - Python 3.11.7
MacOS - Ventura 13.6
pip version - 24.0

Traceback 
```
>>> import pyamg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/__init__.py", line 11, in <module>
    from . import (aggregation, amg_core, classical, gallery, krylov, relaxation, util, vis)
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/aggregation/__init__.py", line 3, in <module>
    from .adaptive import adaptive_sa_solver
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/aggregation/adaptive.py", line 8, in <module>
    from ..multilevel import MultilevelSolver
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/multilevel.py", line 12, in <module>
    from . import krylov
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/__init__.py", line 32, in <module>
    from ._gmres import gmres
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/_gmres.py", line 4, in <module>
    from ._gmres_mgs import gmres_mgs
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/_gmres_mgs.py", line 9, in <module>
    from ..util.linalg import norm
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/util/__init__.py", line 4, in <module>
    from . import utils
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/util/utils.py", line 32, in <module>
    from .. import amg_core
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/amg_core/__init__.py", line 3, in <module>
    from .evolution_strength import (apply_absolute_distance_filter, apply_distance_filter,
ModuleNotFoundError: No module named 'pyamg.amg_core.evolution_strength'
```
