### ISSUE TITLE
block GS default not robust

### ISSUE THREAD

**Issue by bensworth** [pyamg/pyamg#361]
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyamg/aggregation/pairwise.py", line 105, in pairwise_solver
    change_smoothers(ml, presmoother, postsmoother)
  File "/usr/local/lib/python3.9/site-packages/pyamg/relaxation/smoothing.py", line 367, in change_smoothers
    ml.levels[i].presmoother = setup_presmoother(ml.levels[i], **kwargs1)
  File "/usr/local/lib/python3.9/site-packages/pyamg/relaxation/smoothing.py", line 601, in setup_block_gauss_seidel
    Dinv = get_block_diag(lvl.A, blocksize=blocksize, inv_flag=True)
  File "/usr/local/lib/python3.9/site-packages/pyamg/util/utils.py", line 634, in get_block_diag
    if np.mod(A.shape[0], blocksize) != 0:
TypeError: unsupported operand type(s) for %: 'int' and 'NoneType'
```
We have some solvers that default to, e.g., block GS smoothing, but if we pass in a csr_matrix for A this appears to cause problems. I think we should design the smoothing so that by default if A is BSR, we use a block relaxation, but if A is csr, we do not.

**Comment by bensworth** [comment]
Not reproducible now, classical, pairwise, and sa all work w/ CSR or BSR matrix
