### ISSUE TITLE
ModuleNotFoundError when importing pyamg

### ISSUE THREAD

**Issue by Sushmey** [pyamg/pyamg#411]
Hi there, I was trying to install pyamg on my local but I kept running into this error when importing it. I've tried installing using both `pip install pyamg` and `pip install .` 
Tried uninstalling, reinstalling and force reinstalling but to no avail. 

Local details - 
Python version - 3.11.7
pip version - 24.0
MacOS - Ventura 13.6

Traceback 
```
>>> import pyamg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/__init__.py", line 11, in <module>
    from . import (aggregation, amg_core, classical, gallery, krylov, relaxation, util, vis)
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/aggregation/__init__.py", line 3, in <module>
    from .adaptive import adaptive_sa_solver
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/aggregation/adaptive.py", line 8, in <module>
    from ..multilevel import MultilevelSolver
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/multilevel.py", line 12, in <module>
    from . import krylov
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/__init__.py", line 32, in <module>
    from ._gmres import gmres
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/_gmres.py", line 4, in <module>
    from ._gmres_mgs import gmres_mgs
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/krylov/_gmres_mgs.py", line 9, in <module>
    from ..util.linalg import norm
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/util/__init__.py", line 4, in <module>
    from . import utils
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/util/utils.py", line 32, in <module>
    from .. import amg_core
  File "/Users/sushmey/Documents/Sushmey/GitHub/pyamg/pyamg/amg_core/__init__.py", line 3, in <module>
    from .evolution_strength import (apply_absolute_distance_filter, apply_distance_filter,
ModuleNotFoundError: No module named 'pyamg.amg_core.evolution_strength'
```

**Comment by lukeolson** [comment]
Are you importing while in the source directory by chance?

**Comment by Sushmey** [comment]
I was, yes. Thanks for the reply! Changed directory to the inner pyamg directory and now no more error.
